#ifndef CONSTANTS_H
#define CONSTANTS_H

extern const char* FILE_EXTENSION_COMPRESS;
extern const char* FILE_EXTENSION_DECOMPRESS;
extern const char* FILE_OUTPUT_NAME_NO_EXT;
extern const int FILENAME_BUFFER_SIZE;
typedef enum {
    SUCCESS,
    ERROR_FILE_NOT_FOUND,
    ERROR_FILE_EMPTY,
    ERROR_MEMORY_ALLOCATION,
    ERROR_READ_FAILED,
    ERROR_LOGIC_FAILED,
    ERROR_WRITE_FAILED,
    ERROR_MISSING_ARGUMENT,
    ERROR_ARGUMENT_NUMBER_EXCEEDED,
    ERROR_UNKNOWN_FLAG
} ErrorCode;

#endif